# Generated by Django 4.0.6 on 2022-08-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
